import "bootstrap-icons/font/bootstrap-icons.css";
import "../styles/index.scss";
import Head from 'next/head'
import Nav from "./components/Nav";

function MyApp({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Camila Lemos</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Nav></Nav>
      <Component {...pageProps} />
    </>
  );
}

export default MyApp;
